Changed filenames to tsx, added types
nadja-po/renome-typescript pull request #1
Opened 2021-04-29 06:12 UTC by nadja-po

Changed filenames to tsx, fixed all TypeScript errors, changed files according to TypeScript.

2021-04-29 06:33 UTC, ArtemsBoroviks requested changes

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/App.tsx
> +  const [dataJson, setDataJson] = useState<any>([]);
Avoid to use "any" type

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/molecules/AboutPart/index.tsx
> +  imagesAbout: Array<{ src: string, alt: string }>,
Define interface for this, and use like this "Images[]"

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/molecules/Footer/index.tsx
> +  iconsFooter: Array<{ id: number, src: string, alt: string }>,
as above define interface and use like this FooterIcons[]

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/molecules/Gallery/index.tsx
> +  imagesGallery: Array<{ id: number, src: string, alt: string }>,
as above comment define interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Cart/index.tsx
> +  cartItems: Array<{ id: number, title: string, url: string }>,
as above interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Menu/index.tsx
> +  menuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Menu/index.tsx
> +  submenuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Navbar/index.tsx
> +  cartItems: Array<{ id: number, title: string, url: string }>,
interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Navbar/index.tsx
> +  menuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Navbar/index.tsx
> +  submenuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
interface

2021-04-29 06:33 UTC, ArtemsBoroviks commented on src/components/organisms/Slider/index.tsx
> +  imagesCarousel: Array<{ id: number, src: string, alt: string }>,
interface

2021-05-03 06:47 UTC, nadja-po commented on src/components/molecules/AboutPart/index.tsx
> +  imagesAbout: Array<{ src: string, alt: string }>,
Added interface

2021-05-03 06:47 UTC, nadja-po commented on src/components/molecules/Footer/index.tsx
> +  iconsFooter: Array<{ id: number, src: string, alt: string }>,
Added interface

2021-05-03 06:47 UTC, nadja-po commented on src/components/molecules/Gallery/index.tsx
> +  imagesGallery: Array<{ id: number, src: string, alt: string }>,
Added interface

2021-05-03 06:47 UTC, nadja-po commented on src/components/organisms/Cart/index.tsx
> +  cartItems: Array<{ id: number, title: string, url: string }>,
Added interface

2021-05-03 06:48 UTC, nadja-po commented on src/components/organisms/Menu/index.tsx
> +  menuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
Added interface

2021-05-03 06:48 UTC, nadja-po commented on src/components/organisms/Menu/index.tsx
> +  submenuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
Added interface

2021-05-03 06:48 UTC, nadja-po commented on src/components/organisms/Navbar/index.tsx
> +  cartItems: Array<{ id: number, title: string, url: string }>,
Added interface

2021-05-03 06:48 UTC, nadja-po commented on src/components/organisms/Navbar/index.tsx
> +  menuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
Added interface

2021-05-03 06:48 UTC, nadja-po commented on src/components/organisms/Navbar/index.tsx
> +  submenuItems: Array<{ id: number, title: string, url: string, button: boolean, onclick: boolean }>,
Added interface

2021-05-03 06:48 UTC, nadja-po commented on src/components/organisms/Slider/index.tsx
> +  imagesCarousel: Array<{ id: number, src: string, alt: string }>,
Added interface

2021-05-05 11:31 UTC, ArtemsBoroviks commented on src/App.tsx
> +  const [dataJson, setDataJson] = useState<any>([]);
Other thinks are fine, what about this?

2021-05-06 06:40 UTC, nadja-po commented on src/App.tsx
> +  const [dataJson, setDataJson] = useState<any>([]);
I couldn't find the right type in this case.

2021-05-06 09:10 UTC, ArtemsBoroviks commented on src/App.tsx
> +  const [dataJson, setDataJson] = useState<any>([]);
Check this topic
https://www.carlrippon.com/typed-usestate-with-typescript/

2021-05-06 12:06 UTC, ArtemsBoroviks approved these changes

2021-05-06 12:08 UTC, nadja-po commented on src/App.tsx
> +  const [dataJson, setDataJson] = useState<any>([]);
Fixed: changed type Data instead any type, added checking for undefined.

2021-05-09 16:07 UTC, merged